title: Yet Another RussNet
description: Yet Another RussNet aims at creating a large electronic thesaurus for Russian using crowdsourcing.
baseurl: ""
url: "https://russianword.net"
github_username: russianwordnet
theme: minima
plugins:
- jekyll-redirect-from
exclude:
- Gemfile*
- README.md
- CNAME
safe: true
timezone: Europe/Moscow
encoding: UTF-8
